### PR TITLE
Component refactoring and small fixes

### PR DESCRIPTION
**Pull request by svajoklis-1**
Nice project! I have thought about doing something like this myself, though I never got around to it. Did you complete nand2tetris? I am in the middle of it, it's very good.

What I did for this PR is refactor component structs from SomethingComp to Something and renamed all Something() methods do doSomething(). I also created constructors for each component.

IMHO it makes more sense to have the main struct as just "Component" instead of "ComponentComp" and all actions associated with it as verbSomething.

Haven't done much else yet, but I think it's a step into the right direction, let me know what you think.

### CODE REVIEW

**Comment by rzscheck** [comment]
Thanks! I have not actually done nand2tetris. I've read some snippets of the book, which helped me figure out the multibyte RAM. Other than that, I've based it entirely off of nandgame, which in turn is based off nand2tetris (with the exception that I'm doing 8-bit instead of 16-bit).
Your naming method does make more sense. I just went with the first thing that came to my mind. On my first attempt I didn't use structs. I just had a function for each gate/component which worked fine until I got to the memory components that have to hold state. I realized I needed more and added the structs named ComponentComp because my functions were already called Component().

**Comment by rzscheck** [comment]
Of course now that the forward declarations are gone we need to move the Component() functions before the initComponent() functions.

**Comment by rzscheck** [comment]
Additionally we need to change the function calls within functions, such as the call to Mux8() inside doUnary()

**Comment by rzscheck** [comment]
and finish refactoring the rest of the components

**Comment by svajoklis-1** [comment]
I have completely missed refactoring components.h/c, I will do that in my next pull request :|

**Pull request merged**
